INSERT INTO aviacompany(aviacomp_name) VALUES ('Dexter')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Avia-Sibir')
INSERT INTO aviacompany(aviacomp_name) VALUES ('AVIAPARK')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Avrora')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Pegas Fly')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Red Wings')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Ural Airlines')
INSERT INTO aviacompany(aviacomp_name) VALUES ('S7 Airlines')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Aeroflot')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Pobeda')
INSERT INTO aviacompany(aviacomp_name) VALUES ('Emirates')
INSERT INTO aviacompany(aviacomp_name) VALUES ('American Airlines Group')