INSERT INTO department(dep_name) VALUES ('пилот')
INSERT INTO department(dep_name) VALUES ('диспетчер')
INSERT INTO department(dep_name) VALUES ('тех. работник')
INSERT INTO department(dep_name) VALUES ('кассир')
INSERT INTO department(dep_name) VALUES ('охранник')
INSERT INTO department(dep_name) VALUES ('служащий справочного бюро')
INSERT INTO department(dep_name) VALUES ('начальник пилотов')
INSERT INTO department(dep_name) VALUES ('начальник диспетчеров')
INSERT INTO department(dep_name) VALUES ('начальник тех. работников')
INSERT INTO department(dep_name) VALUES ('начальник кассиров')
INSERT INTO department(dep_name) VALUES ('начальник охраны')
INSERT INTO department(dep_name) VALUES ('начальник справочного бюро')