INSERT INTO department(dep_name) VALUES ('пилот')
INSERT INTO department(dep_name) VALUES ('диспетчер')
INSERT INTO department(dep_name) VALUES ('тех. работник')
INSERT INTO department(dep_name) VALUES ('кассир')
INSERT INTO department(dep_name) VALUES ('охранник')
INSERT INTO department(dep_name) VALUES ('служащий справочного бюро')