INSERT INTO timetable(trip_id, trip_status_id) VALUES (1, 5)
INSERT INTO timetable(trip_id, trip_status_id) VALUES (2, 4)
INSERT INTO timetable(trip_id, trip_status_id) VALUES (3, 3)
INSERT INTO timetable(trip_id, trip_status_id) VALUES (4, 5)
INSERT INTO timetable(trip_id, trip_status_id) VALUES (5, 1)
INSERT INTO timetable(trip_id, trip_status_id) VALUES (6, 2)