INSERT INTO tripType(trip_type_name) VALUES ('внутренний')
INSERT INTO tripType(trip_type_name) VALUES ('международный')
INSERT INTO tripType(trip_type_name) VALUES ('чартерный')
INSERT INTO tripType(trip_type_name) VALUES ('грузоперевозочный')
INSERT INTO tripType(trip_type_name) VALUES ('специальный')