INSERT INTO tripStatus(trip_status_name, trip_status_reason) VALUES ('отложен', 'плохие погодные условия')
INSERT INTO tripStatus(trip_status_name, trip_status_reason) VALUES ('отложен', 'технические проблемы')
INSERT INTO tripStatus(trip_status_name, trip_status_reason) VALUES ('отменен', 'продано недостаточно билетов')
INSERT INTO tripStatus(trip_status_name) VALUES ('отменен')
INSERT INTO tripStatus(trip_status_name) VALUES ('по расписанию')