INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Ivanov', 'Sergei', 'Petrovych', 40, 1, 0, 1, 1)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Smirnova', 'Anna', 'Nikolaevna', 35, 2, 2, 1, 2)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Sobolev', 'Anton', 'Vladimirovich', 42, 1, 1, 2, 3)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Popov', 'Semen', 'Vasilyevich', 39, 1, 3, 2, 4)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Sokolova', 'Maria', 'Andreevna', 25, 2, 0, 3)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Petrov', 'Sergei', 30, 1, 2, 3)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Kobeleva', 'Galina', 'Nikolaevna', 48, 2, 2, 4)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Antonova', 'Antonina', 'Vladlenovna', 50, 2, 3, 5)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Sergeev', 'Maksim', 27, 1, 0, 6)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Sharapov', 'Petr', 'Mihaylovich', 23, 1, 0, 7)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Zimin', 'Aleksandr', 'Vitalyevich', 31, 1, 3, 8)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Konev', 'Gennadiy', 57, 1, 7, 9)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Konev', 'Roman', 'Gennadyevich', 20, 1, 0, 9)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Klyuchevskaya', 'Kristina', 'Romanovna', 48, 2, 1, 10)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Romanovich', 'Leonid', 'Ilyich', 35, 1, 2, 11)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Filov', 'Timur', 39, 1, 0, 12)