INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Иванов', 'Сергей', 'Петрович', 40, 1, 0, 1, 1)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Романов', 'Роман', 'Романович', 35, 1, 2, 13)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Сидорова', 'Анна', 'Витальевна', 50, 2, 1, 15)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Смирнова', 'Анна', 'Николаевна', 35, 2, 2, 1, 2)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Соболев', 'Антон', 'Владимирович', 42, 1, 1, 2, 3)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id, med_id) VALUES('Попов', 'Семён', 'Васильевич', 39, 1, 3, 2, 4)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Соколова', 'Мария', 'Андреевна', 25, 2, 0, 3)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Петров', 'Сергей', 30, 1, 2, 3)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Кобелева', 'Галина', 'Николаевна', 48, 2, 2, 4)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Антонова', 'Антонина', 'Владленовна', 50, 2, 3, 5)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Сергеев', 'Максим', 27, 1, 0, 6)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Шарапов', 'Пётр', 'Михайлович', 23, 1, 0, 7)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Зимин', 'Александр', 'Витальевич', 31, 1, 3, 8)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Конев', 'Геннадий', 57, 1, 7, 9)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Конев', 'Роман', 'Геннадьевич', 20, 1, 0, 9)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Ключевская', 'Кристина', 'Романовна', 48, 2, 1, 10)
INSERT INTO workers(worker_lastname, worker_firstname, worker_middlename, worker_age, gen_id, worker_child_count, car_id) VALUES('Романович', 'Леонид', 'Ильич', 35, 1, 2, 11)
INSERT INTO workers(worker_lastname, worker_firstname, worker_age, gen_id, worker_child_count, car_id) VALUES('Филов', 'Тимур', 39, 1, 0, 12)